### PR TITLE
Changed Dto's

### PR DESCRIPTION
**Pull request by rzemekw**

### CODE REVIEW

**Comment by xdab** [comment]
what happonn here?

**Comment by PrzemyslawWcislo** [comment]
checcs have not complete

**Comment by rzemekw** [comment]
All good specification is shit

**Comment by rzemekw** [comment]
Why delete

**Comment by PrzemyslawWcislo** [comment]
KURRRRRWAAAaaaaa

**Comment by PrzemyslawWcislo** [comment]
https://www.sexportal-vergleich.com/wp-content/uploads/reifeladies18-portal.jpg

**Comment by rzemekw** [comment]
https://www.youtube.com/watch?v=M3vd3Qu2bCI

**Comment by PrzemyslawWcislo** [comment]
WE COMUNNISTATE HERE!

**Review by xdab — APPROVED** [review]
this is some quality code

**Pull request merged**
